version: '3'

services:

  mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  tokenapi:
    build:
      context: ../../tokenapi/
    ports:
      - "8082:8082"
    links:
      - mongodb
      - redis
    environment:
      SPRING_APPLICATION_NAME: tokenapi
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/auth
      SPRING_REDIS_HOST: redis

  learningsession:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
      - redis
    environment:
        SPRING_APPLICATION_NAME: learningsession
        SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test