apiVersion: v1
kind: Service
metadata:
  name: tokenapi
  labels:
    app: tokenapi

spec:
  type: NodePort
  selector:
    app: tokenapi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
