apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tokenapi
spec:
  selector:
    matchLabels:
      app: tokenapi
  replicas: 1
  template:
    metadata:
      labels:
        app: tokenapi
    spec:
      containers:
        - image: janisardel/luuleta-token:latest
          name: tokenapi
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/test
          ports:
            - containerPort: 8080
