apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jobswiper
spec:
  selector:
    matchLabels:
      app: jobswiper
  replicas: 2
  template:
    metadata:
      labels:
        app: jobswiper
    spec:
      containers:
        - name: jobswiper
          image: janisardel/luuleta
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/test
            - name: TOKENAPI_BASE_URL
              value: http://tokenapi
            - name: TOKENAPI_BASE_PORT
              value: "8082"
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management